language: python

python:
  - "3.6.8"

services:
  - docker

before_script:
  - pip install docker-compose
  - echo SECRET_KEY >> cfg
  - echo >> cfg
  - echo no >> cfg
  - ./deploy/deploy_containers < cfg
  - entrypoint="$(echo "$(cat deploy/entrypoint.sh)")"
  - entrypoint="${entrypoint/cd code/}"
  - echo "${entrypoint/gunicorn library.wsgi:application -b 0.0.0.0:8080/python \/code\/library\/manage.py test main}" > deploy/entrypoint.sh

script:
  - docker-compose run web sh -c "echo Passed all tests!"
