  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=weblib
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      image: weblib
      ports:
        - "0.0.0.0:8800:8080"
      depends_on:
        - db
