
name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.8, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install docker-compose
      - name: Configure app
        run: |
          echo SECRET_KEY >> cfg
          echo >> cfg
          echo no >> cfg
          ./deploy/deploy_containers < cfg
          entrypoint="$(echo "$(cat deploy/entrypoint.sh)")"
          entrypoint="${entrypoint/cd code/}"
          echo "${entrypoint/gunicorn library.wsgi:application -b 0.0.0.0:8080/python \/code\/library\/manage.py test main}" > deploy/entrypoint.sh
      - name: Build docker container & running tests
        run: |
          docker-compose run web sh -c "echo Passed all tests!"
