name: Ubuntu

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.8, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Running PostgreSQL container
        run: |
          docker run -p 0.0.0.0:5432:5432 \
            -e POSTGRES_DB=weblib \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -d postgres
      - name: Congigure & build app
        run: |
          settings="$(echo "$(cat library/library/settings.py)")"
          echo "${settings/172.17.0.2/localhost}" > library/library/settings.py
          python -m venv venv
          ./venv/bin/python -m pip install -r requirements.txt
      - name: Applying database migrations
        run: |
          ./venv/bin/python ./library/manage.py migrate
          ./venv/bin/python ./library/manage.py makemigrations main
          ./venv/bin/python ./library/manage.py migrate main
      - name: Running tests
        run: |
          ./venv/bin/python ./library/manage.py test main
